<html>
   <?php
  
     ?>
    <body>
        <h1>Hier sind deine Daten:</h1>
        <div>
            
        <p>
        Benutzername: <?=$username?><br>    
        Vorname: <?=$firstName?><br>
            Name: <?=$name?><br>
            Geburtsdatum: <?=$birthdate?><br>
            Email-Adresse: <?=$emailAdress?><br>
            Passwort: <?=$password?><br>
            UserID= <?=$userID?><br>
            <button><a href="index.php?_url=updateUserdata/updateUserdata"> Daten ändern</a></button>
        </div>
    </body>
</html>
